server:
  port: 8081
security:
  user:
    password: root
    name: root
eureka:
  instance:
    prefer-ip-address: true 
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://peer1:8080/eureka/
  server:
    enable-self-preservation: false
  instance:
    hostname: peer2
spring:
  profiles: peer2
  application: 
    name: com.yhem.yunmirror/eureka-server
    
