server:
  port: 9060

spring:
  application:
    name: auth2.0-center
  zipkin:
      base-url: http://localhost:9050
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/zuul-auth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    druid:
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: os1
    port: 6379
eureka:
  instance:
    prefer-ip-address: true 
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://root:root@192.168.223.140:8080/eureka/
endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        web: info
